### ISSUE TITLE
[FEAT]댓글 도메인 및 DTO생성하기

### ISSUE THREAD

**Issue by suyoung503** [OOTVV/SPRINGBOOT#7]
## 목적
>댓글기능추가
## 작업 상세 내용
- [comment entity와 requestDTO responce DTO 만들기]
## 참고 사항

**Comment by sengjun0624** [comment]
좀 더 문서를 디테일하게 작성해주시면 더 좋을것같습니다
 다음에는 우측에 Assignees 랑 label도 같이 달아주세요!
