### ISSUE TITLE
[FEAT] 로그인 구현하기

### ISSUE THREAD

**Issue by seungha123** [OOTVV/SPRINGBOOT#8]
## 목적
>이메일 기반 로그인 구현
>DB 연동 및 테스트 구현
## 작업 상세 내용
- 이메일 기반 아이디와 비밀번호로 회원 가입 후 로그인이 되게 한다
- 아이디는 중복이 되지 않게 한다
- mySQL의 로컬 db와 연동한다
## 참고 사항

**Comment by sengjun0624** [comment]
작업 상세내용 달아주시면 좋을것같아요 :)
